; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Tests for __bf16 (bfloat) soft-promotion on PowerPC.
;
; All PowerPC targets soft-promote bf16 to f32:
;   - Loads/stores use integer lhz/sth (i16 path).
;   - BF16_TO_FP (extend) is done inline via a left-shift of 16 bits.
;   - FP_TO_BF16 (truncate) calls __truncsfbf2.
;   - Arithmetic is performed in f32 and the result truncated back to bf16.

; RUN: llc -mcpu=pwr8 -mtriple=powerpc64le-unknown-unknown \
; RUN:   -verify-machineinstrs -ppc-asm-full-reg-names < %s | FileCheck %s \
; RUN:   --check-prefixes=CHECK,P8
; RUN: llc -mcpu=pwr10 -mtriple=powerpc64le-unknown-unknown \
; RUN:   -verify-machineinstrs -ppc-asm-full-reg-names < %s | FileCheck %s \
; RUN:   --check-prefixes=CHECK,P10

; ---------------------------------------------------------------------------
; Load / store  (bfloat carried as i16 in memory on all targets)
; ---------------------------------------------------------------------------

define void @store_bf16(bfloat %x, ptr %p) nounwind {
; P8-LABEL: store_bf16:
; P8:       # %bb.0:
; P8-NEXT:    sth r3, 0(r4)
; P8-NEXT:    blr
;
; P10-LABEL: store_bf16:
; P10:       # %bb.0:
; P10-NEXT:    sth r3, 0(r4)
; P10-NEXT:    blr
  store bfloat %x, ptr %p
  ret void
}

define bfloat @load_bf16(ptr %p) nounwind {
; P8-LABEL: load_bf16:
; P8:       # %bb.0:
; P8-NEXT:    lhz r3, 0(r3)
; P8-NEXT:    blr
;
; P10-LABEL: load_bf16:
; P10:       # %bb.0:
; P10-NEXT:    lhz r3, 0(r3)
; P10-NEXT:    blr
  %v = load bfloat, ptr %p
  ret bfloat %v
}

; ---------------------------------------------------------------------------
; Extend bfloat -> float  (left-shift 16, no libcall)
; ---------------------------------------------------------------------------

define float @extend_bf16_to_f32(bfloat %a) nounwind {
; CHECK-LABEL: extend_bf16_to_f32:
; CHECK:       # %bb.0:
; CHECK:         slwi r3, r3, 16
; CHECK:         mtvsrwz
; CHECK:         xscvspdpn
; CHECK-NEXT:    blr
  %r = fpext bfloat %a to float
  ret float %r
}

; ---------------------------------------------------------------------------
; Truncate float -> bfloat  (calls __truncsfbf2)
; ---------------------------------------------------------------------------

define bfloat @trunc_f32_to_bf16(float %a) nounwind {
; CHECK-LABEL: trunc_f32_to_bf16:
; CHECK:       # %bb.0:
; CHECK:         bl __truncsfbf2
  %r = fptrunc float %a to bfloat
  ret bfloat %r
}

; ---------------------------------------------------------------------------
; Arithmetic: addition  (promote both operands, fadd in f32, truncate result)
; ---------------------------------------------------------------------------

define bfloat @add_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: add_bf16:
; CHECK:       # %bb.0:
; CHECK:         slwi {{r[0-9]+}}, {{r[0-9]+}}, 16
; CHECK:         slwi {{r[0-9]+}}, {{r[0-9]+}}, 16
; CHECK:         fadds
; CHECK:         bl __truncsfbf2
  %r = fadd bfloat %a, %b
  ret bfloat %r
}

; ---------------------------------------------------------------------------
; Comparison  (promote both operands to f32, then compare)
; ---------------------------------------------------------------------------

define i1 @cmp_bf16(bfloat %a, bfloat %b) nounwind {
; CHECK-LABEL: cmp_bf16:
; CHECK:       # %bb.0:
; CHECK:         slwi {{r[0-9]+}}, {{r[0-9]+}}, 16
; CHECK:         slwi {{r[0-9]+}}, {{r[0-9]+}}, 16
; CHECK:         fcmpu
  %r = fcmp olt bfloat %a, %b
  ret i1 %r
}

; ---------------------------------------------------------------------------
; Integer to bfloat conversion
; ---------------------------------------------------------------------------

define bfloat @sitofp_i32_to_bf16(i32 %a) nounwind {
; CHECK-LABEL: sitofp_i32_to_bf16:
; CHECK:       # %bb.0:
; CHECK:         bl __truncsfbf2
  %r = sitofp i32 %a to bfloat
  ret bfloat %r
}
