; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Tests for _Float16 (half) soft-promotion on PowerPC.
;
; Sub-P9 (P8): all f16 arithmetic is promoted to f32 via __extendhfsf2 /
; __truncsfhf2 libcalls.  Loads and stores use integer lhz/sth.
;
; P9 (ISA 3.0): load/store use LXSIHZX+XSCVHPDP / XSCVDPHP+STXSIHX.
; Register-to-register FP16_TO_FP / FP_TO_FP16 also use hardware.

; RUN: llc -mcpu=pwr8 -mtriple=powerpc64le-unknown-unknown \
; RUN:   -verify-machineinstrs -ppc-asm-full-reg-names < %s | FileCheck %s \
; RUN:   --check-prefixes=CHECK,P8
; RUN: llc -mcpu=pwr9 -mtriple=powerpc64le-unknown-unknown \
; RUN:   -verify-machineinstrs -ppc-asm-full-reg-names < %s | FileCheck %s \
; RUN:   --check-prefixes=CHECK,P9

; ---------------------------------------------------------------------------
; Load / store  (half is carried as i16 in memory on both P8 and P9)
; ---------------------------------------------------------------------------

define void @store_f16(half %x, ptr %p) nounwind {
; P8-LABEL: store_f16:
; P8:       # %bb.0:
; P8-NEXT:    sth r3, 0(r4)
; P8-NEXT:    blr
;
; P9-LABEL: store_f16:
; P9:       # %bb.0:
; P9-NEXT:    sth r3, 0(r4)
; P9-NEXT:    blr
  store half %x, ptr %p
  ret void
}

define half @load_f16(ptr %p) nounwind {
; P8-LABEL: load_f16:
; P8:       # %bb.0:
; P8-NEXT:    lhz r3, 0(r3)
; P8-NEXT:    blr
;
; P9-LABEL: load_f16:
; P9:       # %bb.0:
; P9-NEXT:    lhz r3, 0(r3)
; P9-NEXT:    blr
  %v = load half, ptr %p
  ret half %v
}

; ---------------------------------------------------------------------------
; Arithmetic: addition  (soft-promote to f32 on P8, same on P9)
; ---------------------------------------------------------------------------

define half @add_f16(half %a, half %b) nounwind {
; P8-LABEL: add_f16:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    mr r4, r3
; P8-NEXT:    srwi r3, r3, 16
; P8-NEXT:    bl __extendhfsf2
; P8-NEXT:    fmr f2, f1
; P8-NEXT:    mr r3, r4
; P8-NEXT:    bl __extendhfsf2
; P8-NEXT:    fadds f1, f1, f2
; P8-NEXT:    bl __truncsfhf2
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
  %r = fadd half %a, %b
  ret half %r
}

; ---------------------------------------------------------------------------
; Extend f16 -> f32  (soft: libcall on P8, hardware XSCVHPDP on P9)
; ---------------------------------------------------------------------------

define float @extend_f16_to_f32(half %a) nounwind {
; P8-LABEL: extend_f16_to_f32:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    bl __extendhfsf2
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: extend_f16_to_f32:
; P9:       # %bb.0:
; P9-NEXT:    mtvsrwz v2, r3
; P9-NEXT:    xscvhpdp f1, v2
; P9-NEXT:    frsp f1, f1
; P9-NEXT:    blr
  %r = fpext half %a to float
  ret float %r
}

; ---------------------------------------------------------------------------
; Truncate f32 -> f16  (soft: libcall on P8, hardware XSCVDPHP on P9)
; ---------------------------------------------------------------------------

define half @trunc_f32_to_f16(float %a) nounwind {
; P8-LABEL: trunc_f32_to_f16:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    bl __truncsfhf2
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: trunc_f32_to_f16:
; P9:       # %bb.0:
; P9-NEXT:    xscvdphp v2, f1
; P9-NEXT:    mfvsrwz r3, v2
; P9-NEXT:    blr
  %r = fptrunc float %a to half
  ret half %r
}

; ---------------------------------------------------------------------------
; Extend load: f16 mem -> f64  (LXSIHZX+XSCVHPDP on P9)
; ---------------------------------------------------------------------------

define double @extload_f16_to_f64(ptr %p) nounwind {
; P8-LABEL: extload_f16_to_f64:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    lhz r3, 0(r3)
; P8-NEXT:    bl __extendhfsf2
; P8-NEXT:    frsp f1, f1
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: extload_f16_to_f64:
; P9:       # %bb.0:
; P9-NEXT:    lxsihzx v2, 0, r3
; P9-NEXT:    xscvhpdp f1, v2
; P9-NEXT:    blr
  %v = load half, ptr %p
  %r = fpext half %v to double
  ret double %r
}

; ---------------------------------------------------------------------------
; Truncate store: f64 -> f16 mem  (XSCVDPHP+STXSIHX on P9)
; ---------------------------------------------------------------------------

define void @truncstore_f64_to_f16(double %v, ptr %p) nounwind {
; P8-LABEL: truncstore_f64_to_f16:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    frsp f1, f1
; P8-NEXT:    bl __truncsfhf2
; P8-NEXT:    sth r3, 0(r4)
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: truncstore_f64_to_f16:
; P9:       # %bb.0:
; P9-NEXT:    xscvdphp v2, f1
; P9-NEXT:    stxsihx v2, 0, r3
; P9-NEXT:    blr
  %t = fptrunc double %v to half
  store half %t, ptr %p
  ret void
}

; ---------------------------------------------------------------------------
; Comparison: result is i1, operands promoted to f32 first
; ---------------------------------------------------------------------------

define i1 @cmp_f16(half %a, half %b) nounwind {
; P8-LABEL: cmp_f16:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    mr r4, r3
; P8-NEXT:    srwi r3, r3, 16
; P8-NEXT:    bl __extendhfsf2
; P8-NEXT:    fmr f2, f1
; P8-NEXT:    mr r3, r4
; P8-NEXT:    bl __extendhfsf2
; P8-NEXT:    fcmpu cr0, f1, f2
; P8-NEXT:    mfocrf r3, 128
; P8-NEXT:    rlwinm r3, r3, 29, 31, 31
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
  %r = fcmp olt %a, %b
  ret i1 %r
}

; ---------------------------------------------------------------------------
; Integer to f16 conversion
; ---------------------------------------------------------------------------

define half @sitofp_i32_to_f16(i32 %a) nounwind {
; P8-LABEL: sitofp_i32_to_f16:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    std r0, 16(r1)
; P8-NEXT:    stdu r1, -32(r1)
; P8-NEXT:    bl __floatsisf
; P8-NEXT:    bl __truncsfhf2
; P8-NEXT:    addi r1, r1, 32
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
  %r = sitofp i32 %a to half
  ret half %r
}
